/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Oct 11 17:30:10 2016
 * --------------------------------------------------------
 *
 */
#ifndef USERMODEL_h
#define USERMODEL_h

//#include "lut.h"


#include "mbs_user_interface.h"
// ============================================================ //


struct UserModel 
{
    struct wheel_ft{
        double K_tire;
        double D_tire;
        double r_n_tire;
        double r_t_tire;
    } wheel_ft;
 
    struct wheel_rr{
        double K_tire;
        double D_tire;
        double r_n_tire;
        double r_t_tire;
    } wheel_rr;
 
    struct shock_ft{
        double K;
        double D;
        double Z_0;
        double Z_min;
        double Z_max;
        double K_stop;
    } shock_ft;
 
    struct shock_rr{
        double K;
        double D;
        double Z_0;
        double Z_min;
        double Z_max;
        double K_stop;
    } shock_rr;
 
    struct tilting_ctrl{
        double K;
        double Ki;
        double Kd;
    } tilting_ctrl;
 
    struct steering_box{
        double K;
    } steering_box;
 
    struct BGC{
        double carrier_ft_lt_to_sterring_rod_ft_lt_width;
    } BGC;
 
    struct pincage{
        double* pin;
    } pincage;
 
    struct lqi{
        int* e;
        // index of the corresponding values in MBSdataStruct->ux/uxd/ux0
    } lqi;
 
    struct energy{
        int* energyE;
        // index of the corresponding values in MBSdataStruct->ux/uxd/ux0
        int* energyM;
        // index of the corresponding values in MBSdataStruct->ux/uxd/ux0
    } energy;
 
};

// ============================================================ //
 
# endif
