/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Nov 17 09:27:23 2016
 * --------------------------------------------------------
 *
 */
#ifndef USERMODEL_h
#define USERMODEL_h

//#include "lut.h"


#include "mbs_user_interface.h"
// ============================================================ //


struct UserModel 
{
    struct wheel_ft{
        double K_tire;
        double D_tire;
        double r_n_tire;
        double r_t_tire;
    } wheel_ft;
 
    struct wheel_rr{
        double K_tire;
        double D_tire;
        double r_n_tire;
        double r_t_tire;
    } wheel_rr;
 
    struct tilting_ctrl{
        double K;
        double Ki;
        double Kd;
    } tilting_ctrl;
 
};

// ============================================================ //
 
# endif
