/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Tue Oct 11 17:30:10 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_7 225
#define M_9 10
#define M_11 3
#define M_17 4.6
#define M_23 4.6

// center of mass
#define L_1_7 -0.6
#define L_3_7 0.3
#define L_3_11 0.16

// inertia
#define IN_1_7 17.5
#define IN_3_7 -7.8
#define IN_5_7 54.6
#define IN_9_7 45.5
#define IN_1_9 0.25
#define IN_5_9 0.5
#define IN_9_9 0.25
#define IN_1_11 0.1
#define IN_5_11 0.02
#define IN_1_17 0.11
#define IN_5_17 0.22
#define IN_9_17 0.11
#define IN_1_23 0.11
#define IN_5_23 0.22
#define IN_9_23 0.11

// body point
#define DPT_1_2 -1.058
#define DPT_3_2 0.112345
#define DPT_1_3 -1.14
#define DPT_3_3 0.5
#define DPT_1_4 -0.6
#define DPT_3_4 0.3
#define DPT_1_5 0.447472
#define DPT_3_5 0.019999
#define DPT_1_6 0.499997
#define DPT_3_6 0.370216
#define DPT_1_7 0.330002
#define DPT_3_7 0.350001
#define DPT_1_8 -0.496298
#define DPT_1_9 -0.21
#define DPT_3_9 0.15
#define DPT_2_11 -1e-06
#define DPT_3_11 1e-06
#define DPT_2_12 1e-06
#define DPT_3_12 1e-06
#define DPT_2_13 -0.05
#define DPT_3_13 0.25
#define DPT_2_14 0.05
#define DPT_3_14 0.25
#define DPT_3_15 0.16
#define DPT_2_16 -0.344932
#define DPT_2_17 -0.22
#define DPT_3_17 1e-06
#define DPT_3_18 0.38
#define DPT_1_19 0.02811
#define DPT_2_19 -0.002053
#define DPT_3_19 0.065002
#define DPT_1_20 0.12
#define DPT_2_20 -0.047817
#define DPT_3_20 0.369999
#define DPT_2_22 0.344932
#define DPT_2_23 0.22
#define DPT_3_23 1e-06
#define DPT_3_24 0.38
#define DPT_1_25 0.02811
#define DPT_2_25 0.002053
#define DPT_3_25 0.065002
#define DPT_1_26 0.12
#define DPT_2_26 0.047817
#define DPT_3_26 0.369999
#define DPT_1_28 0.12
#define DPT_2_28 -0.03
#define DPT_1_29 0.12
#define DPT_2_29 0.03
#define DPT_2_32 -0.311512
#define DPT_2_33 0.311512

// ============================================================ //

# endif
