/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Mon Dec  5 11:13:29 2016
 * --------------------------------------------------------
 *
 */
#ifndef USER_HARD_PARAM_h
#define USER_HARD_PARAM_h

// ============================================================ //


// gravity
#define G_3 -9.81

// mass
#define M_7 14.4
#define M_9 0.2944
#define M_12 0.192
#define M_18 0.2944
#define M_24 0.2944

// center of mass
#define L_1_7 -0.24
#define L_3_7 0.12
#define L_3_12 0.064

// inertia
#define IN_1_7 2.8
#define IN_3_7 -1.248
#define IN_5_7 8.736
#define IN_9_7 7.28
#define IN_1_9 0.0176
#define IN_5_9 0.0352
#define IN_9_9 0.0176
#define IN_1_12 0.04
#define IN_5_12 0.008
#define IN_1_18 0.0176
#define IN_5_18 0.0352
#define IN_9_18 0.0176
#define IN_1_24 0.0176
#define IN_5_24 0.0352
#define IN_9_24 0.0176

// body point
#define DPT_1_2 -0.4232
#define DPT_3_2 0.044938
#define DPT_1_3 -0.4232
#define DPT_3_3 0.2
#define DPT_1_4 -0.24
#define DPT_3_4 0.12
#define DPT_1_5 0.17898
#define DPT_3_5 0.007996
#define DPT_1_6 0.199999
#define DPT_3_6 0.148086
#define DPT_1_7 0.131422
#define DPT_3_7 0.14
#define DPT_1_8 -0.206519
#define DPT_1_9 -0.084
#define DPT_3_9 0.06
#define DPT_3_11 0.05
#define DPT_2_12 -4e-07
#define DPT_3_12 4e-07
#define DPT_2_13 4e-07
#define DPT_3_13 4e-07
#define DPT_2_14 -0.02
#define DPT_3_14 0.1
#define DPT_2_15 0.02
#define DPT_3_15 0.1
#define DPT_3_16 0.064
#define DPT_2_17 -0.137973
#define DPT_2_18 -0.062
#define DPT_3_18 4e-07
#define DPT_3_20 0.152
#define DPT_1_21 0.011244
#define DPT_2_21 -0.0408
#define DPT_3_21 0.026
#define DPT_1_22 0.048
#define DPT_2_22 -0.0188
#define DPT_3_22 0.13799
#define DPT_2_24 0.137973
#define DPT_2_25 0.062
#define DPT_3_25 4e-07
#define DPT_3_27 0.152
#define DPT_1_28 0.011244
#define DPT_2_28 0.0408
#define DPT_3_28 0.026
#define DPT_1_29 0.048
#define DPT_2_29 0.0188
#define DPT_3_29 0.13799
#define DPT_1_31 0.048
#define DPT_2_31 -0.012
#define DPT_1_32 0.048
#define DPT_2_32 0.012
#define DPT_2_35 -0.1246
#define DPT_2_36 0.1246

// ============================================================ //

# endif
