/* --------------------------------------------------------
 * This code was generated automatically by MBsysC modules.
 * MBsysC modules are distributed as part of the ROBOTRAN 
 * software. They provides functionalities for dealing with
 * symbolic equations generated by ROBOTRAN. 
 *
 * More info on www.robotran.be 
 *
 * Universite catholique de Louvain, Belgium 
 *
 * Last update : Thu Nov 17 09:27:23 2016
 * --------------------------------------------------------
 *
 */
#include "mbs_path.h"
#include "user_model.h"
#include "mbs_xml_reader.h"
#include "mbs_load_xml.h"
#include "useful_functions.h"

// ============================================================ //


UserModel* mbs_new_user_model() 
{
    UserModel* um;
    um = (UserModel*)malloc(sizeof(UserModel));
    um->wheel_ft.K_tire = 0.0;
    um->wheel_ft.D_tire = 0.0;
    um->wheel_ft.r_n_tire = 0.0;
    um->wheel_ft.r_t_tire = 0.0;
 
    um->wheel_rr.K_tire = 0.0;
    um->wheel_rr.D_tire = 0.0;
    um->wheel_rr.r_n_tire = 0.0;
    um->wheel_rr.r_t_tire = 0.0;
 
    um->tilting_ctrl.K = 0.0;
    um->tilting_ctrl.Ki = 0.0;
    um->tilting_ctrl.Kd = 0.0;
 
    return um;
}

void mbs_delete_user_model(UserModel* um) 
{
    free(um);
}

 void mbs_load_user_model_xml(MDS_gen_strct* gen, UserModel* um) 
{

    int ind;
    int ind_state_value = 1;

    um->wheel_ft.K_tire = gen->user_models->user_model_list[0]->parameter_list[0]->value_list[0];
    um->wheel_ft.D_tire = gen->user_models->user_model_list[0]->parameter_list[1]->value_list[0];
    um->wheel_ft.r_n_tire = gen->user_models->user_model_list[0]->parameter_list[2]->value_list[0];
    um->wheel_ft.r_t_tire = gen->user_models->user_model_list[0]->parameter_list[3]->value_list[0];
 
    um->wheel_rr.K_tire = gen->user_models->user_model_list[1]->parameter_list[0]->value_list[0];
    um->wheel_rr.D_tire = gen->user_models->user_model_list[1]->parameter_list[1]->value_list[0];
    um->wheel_rr.r_n_tire = gen->user_models->user_model_list[1]->parameter_list[2]->value_list[0];
    um->wheel_rr.r_t_tire = gen->user_models->user_model_list[1]->parameter_list[3]->value_list[0];
 
    um->tilting_ctrl.K = gen->user_models->user_model_list[2]->parameter_list[0]->value_list[0];
    um->tilting_ctrl.Ki = gen->user_models->user_model_list[2]->parameter_list[1]->value_list[0];
    um->tilting_ctrl.Kd = gen->user_models->user_model_list[2]->parameter_list[2]->value_list[0];
 
}

// ============================================================ //
 
